# DO NOT EDIT MANUALLY
# This is an autogenerated file for explicit gem requires.
# Please instead update this file by running `tapioca require`.

# typed: false

require 'bootsnap/setup'
require 'bundler/setup'
require 'rails/all'
require 'test_helper'
require 'uri'
