# DO NOT EDIT MANUALLY
# This is an autogenerated file for explicit gem requires.
# Please instead update this file by running `tapioca require`.
# typed: false
# frozen_string_literal: true

require 'bootsnap/setup'
require 'bundler/setup'
require 'faker'
require 'rails/all'
require 'uri'
