# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `tapioca todo`.

# typed: false

module ::Erubi::Engine; end
module Rake::TaskLib; end
module Ripper::SexpBuilder; end
